### ISSUE TITLE
the slack invitation is not working

### ISSUE THREAD

**Issue by whoisleehom** [aristoteleo/dynamo-tutorials#1]
Excuse me, when I try to join the public slack workspace, it told me the link is no longer valid. Could you please share a new link? Thank you. @Xiaojieqiu

**Comment by Xiaojieqiu** [comment]
@whoisleehom sorry for the delay, this is our site name: dynamo-discussionhq.slack.com

if you can send me your email address, I can add you in too

**Comment by whoisleehom** [comment]
Thank you for your replying. I forgot to check my email and github during Spring Festival. 
This is my official email address: ***@***.***


Yuan Gao


On 2/3/2022 13:24，Xiaojie ***@***.***> wrote：

@whoisleehom sorry for the delay, this is our site name: dynamo-discussionhq.slack.com

if you can send me your email address, I can add you in too

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Xiaojieqiu** [comment]
please send me your email address so I can add you to the slack

**Comment by whoisleehom** [comment]
my email address is gaoyuan01@caas.cn
